### ISSUE TITLE
Some Plroblem

### ISSUE THREAD

**Issue by Sun-Xinnnnn** [dmar-bonn/ipp-marl#2]
Thank you very much for your paper and code, I have successfully run your main.py, but there are still a few points I would like to discuss with you, I would like to know how to generate the figure 1 in the paper? At the same time, I noticed whether the.json plot under the paper_plot file is missing. Finally, I reported an error when running classification.py, and reported an error message：
`episode 300
c_i: 0
Traceback (most recent call last):
  File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1911, in <module>
    main()
  File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1906, in main
    classification.execute()
  File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 129, in execute
    self.split_dataset(batch_memory)
  File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 149, in split_dataset
    training_input, training_labels = add_data(
  File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1130, in add_data
    mlp1 = get_input_mlp1(
  File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1181, in get_input_mlp1
    agent_state_space.index_to_position(
  File "E:\PE\Code\choose\001\ipp-marl-master\marl_framework\agent\state_space.py", line 64, in index_to_position
    self.spacing + state[2] * self.spacing,
IndexError: list index out of range`

**Comment by two-tigger** [comment]
> Thank you very much for your paper and code, I have successfully run your main.py, but there are still a few points I would like to discuss with you, I would like to know how to generate the figure 1 in the paper? At the same time, I noticed whether the.json plot under the paper_plot file is missing. Finally, I reported an error when running classification.py, and reported an error message： `episode 300 c_i: 0 Traceback (most recent call last): File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1911, in <module> main() File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1906, in main classification.execute() File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 129, in execute self.split_dataset(batch_memory) File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 149, in split_dataset training_input, training_labels = add_data( File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1130, in add_data mlp1 = get_input_mlp1( File "E:/PE/Code/choose/001/ipp-marl-master/marl_framework/classification.py", line 1181, in get_input_mlp1 agent_state_space.index_to_position( File "E:\PE\Code\choose\001\ipp-marl-master\marl_framework\agent\state_space.py", line 64, in index_to_position self.spacing + state[2] * self.spacing, IndexError: list index out of range`

你好，请问这个问题解决了吗？

**Comment by zxy-Aug** [comment]
它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。

**Comment by NaLiu613** [comment]
方便加个联系方式讨论一下吗

**Comment by yvpoint** [comment]
> 它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。

你好, 我们最近在做相关工作, 方便交流一下吗?

**Comment by Jiwen97** [comment]
> > 它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。
> 
> 你好, 我们最近在做相关工作, 方便交流一下吗?

你好，可以交流一下进展吗？我的邮箱是xujiwen@link.cuhk.edu.hk

**Comment by Sun-Xinnnnn** [comment]
> 它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。

I have successfully run it, and I think there may be a problem with your environment, although I am not currently working on the application field of UAVs. The following is a simple training logs,  just for reference：

`
----------------------------------- USED HYPERPARAMETERS -----------------------------------

{'environment': {'num_envs': 2, 'seed': 3, 'x_dim': 50, 'y_dim': 50}, 'sensor': {'type': 'rgb_camera', 'field_of_view': {'angle_x': 60, 'angle_y': 60}, 'pixel': {'number_x': 57, 'number_y': 57}, 'encoding': 'rgb8', 'model': {'type': 'altitude_dependent', 'coeff_a': 0.05, 'coeff_b': 0.2}, 'simulation': {'type': 'random_field', 'cluster_radius': 5}}, 'mapping': {'prior': 0.5}, 'experiment': {'title': 'test_experiment', 'constraints': {'spacing': 5, 'min_altitude': 5, 'max_altitude': 15, 'budget': 14, 'num_actions': 6}, 'uav': {'max_v': 5, 'max_a': 2, 'sampling_time': 2, 'communication_range': 25, 'fix_range': True, 'failure_rate': 0}, 'missions': {'type': 'COMA', 'mission_mode': 'training', 'n_episodes': 1500, 'patience': 100, 'n_agents': 4, 'action_space': 'larger', 'planning_uncertainty': 'SE', 'eps_max': 0.5, 'eps_min': 0.02, 'eps_anneal_phase': 10000, 'use_eps': True, 'class_weighting': [0, 1], 'reward_normalization': False}, 'baselines': {'lawnmower': {'trials': 50, 'altitude': 5}, 'random': {'n_episodes': 50}, 'information_gain': {'trials': 50, 'communication': True}}}, 'evaluation': {'repetitions': 1, 'metrics': ['num_waypoints', 'paths', 'rmse', 'wrmse', 'mll', 'wmll', 'run_time']}, 'networks': {'type': 'CNN', 'data_passes': 5, 'batch_size': 60, 'batch_number': 5, 'copy_rate': 10, 'gamma': 0.99, 'lambda': 0.8, 'actor': {'hidden_dim': 128, 'learning_rate': 1e-05, 'momentum': 0.9, 'gradient_norm': 10}, 'critic': {'target_update_mode': 'hard', 'tau': 0.01, 'update_mode': 'random_batches', 'synchronization': 'no', 'fc1_dim': 64, 'learning_rate': 0.0001, 'momentum': 0.9, 'gradient_norm': 10}}, 'classification': {'n_episodes': 2, 'data_split': [0.4, 0.4, 0.2], 'number_epochs': 100, 'batch_size': 50}}

-------------------------------------- START PIPELINE --------------------------------------

Training step: 1
Environment step: 300
Training step: 2
Environment step: 600
Training step: 3
Environment step: 900
Training step: 4
Environment step: 1200
Training step: 5
Environment step: 1500
Training step: 6
Environment step: 1800
Training step: 7
Environment step: 2100
Training step: 8
Environment step: 2400
Training step: 9
Environment step: 2700
Training step: 10
Environment step: 3000
Training step: 11
Environment step: 3300

`

**Comment by Sun-Xinnnnn** [comment]
> 它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。

I have successfully run it, and I think there may be a problem with your environment, although I am not currently working on the application field of UAVs. The following is a simple training logs,  just for reference：

`-----------------------------------` USED HYPERPARAMETERS -----------------------------------

{'environment': {'num_envs': 2, 'seed': 3, 'x_dim': 50, 'y_dim': 50}, 'sensor': {'type': 'rgb_camera', 'field_of_view': {'angle_x': 60, 'angle_y': 60}, 'pixel': {'number_x': 57, 'number_y': 57}, 'encoding': 'rgb8', 'model': {'type': 'altitude_dependent', 'coeff_a': 0.05, 'coeff_b': 0.2}, 'simulation': {'type': 'random_field', 'cluster_radius': 5}}, 'mapping': {'prior': 0.5}, 'experiment': {'title': 'test_experiment', 'constraints': {'spacing': 5, 'min_altitude': 5, 'max_altitude': 15, 'budget': 14, 'num_actions': 6}, 'uav': {'max_v': 5, 'max_a': 2, 'sampling_time': 2, 'communication_range': 25, 'fix_range': True, 'failure_rate': 0}, 'missions': {'type': 'COMA', 'mission_mode': 'training', 'n_episodes': 1500, 'patience': 100, 'n_agents': 4, 'action_space': 'larger', 'planning_uncertainty': 'SE', 'eps_max': 0.5, 'eps_min': 0.02, 'eps_anneal_phase': 10000, 'use_eps': True, 'class_weighting': [0, 1], 'reward_normalization': False}, 'baselines': {'lawnmower': {'trials': 50, 'altitude': 5}, 'random': {'n_episodes': 50}, 'information_gain': {'trials': 50, 'communication': True}}}, 'evaluation': {'repetitions': 1, 'metrics': ['num_waypoints', 'paths', 'rmse', 'wrmse', 'mll', 'wmll', 'run_time']}, 'networks': {'type': 'CNN', 'data_passes': 5, 'batch_size': 60, 'batch_number': 5, 'copy_rate': 10, 'gamma': 0.99, 'lambda': 0.8, 'actor': {'hidden_dim': 128, 'learning_rate': 1e-05, 'momentum': 0.9, 'gradient_norm': 10}, 'critic': {'target_update_mode': 'hard', 'tau': 0.01, 'update_mode': 'random_batches', 'synchronization': 'no', 'fc1_dim': 64, 'learning_rate': 0.0001, 'momentum': 0.9, 'gradient_norm': 10}}, 'classification': {'n_episodes': 2, 'data_split': [0.4, 0.4, 0.2], 'number_epochs': 100, 'batch_size': 50}}

-------------------------------------- START PIPELINE --------------------------------------

Training step: 1
Environment step: 300
Training step: 2
Environment step: 600
Training step: 3
Environment step: 900
Training step: 4
Environment step: 1200
Training step: 5
Environment step: 1500
Training step: 6
Environment step: 1800
Training step: 7
Environment step: 2100
Training step: 8
Environment step: 2400
Training step: 9
Environment step: 2700
Training step: 10
Environment step: 3000
Training step: 11
Environment step: 3300`

**Comment by Sun-Xinnnnn** [comment]
> > > 它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。
> > 
> > 
> > 你好, 我们最近在做相关工作, 方便交流一下吗?
> 
> 你好，可以交流一下进展吗？我的邮箱是[xujiwen@link.cuhk.edu.hk](mailto:xujiwen@link.cuhk.edu.hk)

I have made a reply above, just for reference

**Comment by Jiwen97** [comment]
> > > > 它这个代码是不是就没办法仿真，有没有可实现的办法，是我们笨还是有造假的嫌疑？。。。
> > > 
> > > 
> > > 你好, 我们最近在做相关工作, 方便交流一下吗?
> > 
> > 
> > 你好，可以交流一下进展吗？我的邮箱是[xujiwen@link.cuhk.edu.hk](mailto:xujiwen@link.cuhk.edu.hk)
> 
> I have made a reply above, just for reference

Thank you for your reply. I have trained it as well. Have you make a visualization of its trajectory result as in figure 1 in the paper? Hope to get hint from your attempt.

**Comment by sssn-tech** [comment]
> xujiwen@link.cuhk.edu.hk

I have reviewed the repo and found no code about figure 1. , It might be a sketch map.
